# Generated by Django 5.2 on 2025-06-05 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_nerattribute_peopleattribute_placeattribute_and_more")
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=20)),
                ("target", models.CharField(max_length=20)),
                ("label", models.CharField(max_length=30)),
                ("metaData", models.CharField(max_length=100)),
                (
                    "entityID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="main.newsarticle",
                    ),
                ),
            ],
        )
    ]
