# Generated by Django 5.2 on 2025-06-27 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_newsarticle_result_obj_newsarticle_result_pos_and_more")
    ]

    operations = [
        migrations.AlterField(
            model_name="newsarticle",
            name="published_at",
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
