# Generated by Django 5.2 on 2025-06-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0012_alter_newsarticle_published_at_and_more")]

    operations = [
        migrations.AlterField(
            model_name="newsarticle",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        )
    ]
