# Generated by Django 5.2 on 2025-06-04 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_ner_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='NERAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('value', models.CharField(max_length=15)),
                ('entityid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='main.ner')),
            ],
        ),
        migrations.CreateModel(
            name='PeopleAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('value', models.CharField(max_length=15)),
                ('entityid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='main.people')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('value', models.CharField(max_length=15)),
                ('entityid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='main.place')),
            ],
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
    ]
