# Generated by Django 5.2 on 2025-06-05 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("main", "0005_event")]

    operations = [
        migrations.RenameField(
            model_name="event", old_name="entityID", new_name="entityid"
        )
    ]
