# Generated by Django 5.2 on 2025-06-05 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0007_alter_newsarticle_content")]

    operations = [
        migrations.AddField(
            model_name="event",
            name="encouner_time",
            field=models.DateTimeField(blank=True, null=True),
        )
    ]
