# Generated by Django 5.2 on 2025-06-12 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0009_rename_encouner_time_event_encounter_time")]

    operations = [
        migrations.AddField(
            model_name="event", name="url", field=models.URLField(blank=True, null=True)
        )
    ]
