# Generated by Django 5.2 on 2025-06-05 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0006_rename_entityid_event_entityid")]

    operations = [
        migrations.AlterField(
            model_name="newsarticle",
            name="content",
            field=models.TextField(unique=True),
        )
    ]
